spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      routes:
        - id: newspaper_service
          uri: http://localhost:8080
          predicates:
            - Path=/api/newspaper/**
          filters:
            - AuthenticationFilter

        - id: subscription_service
          uri: http://localhost:8081
          predicates:
            - Path=/api/subscription/**
          filters:
            - AuthenticationFilter

        - id: inventory_service
          uri: http://localhost:8082
          predicates:
            - Path=/api/inventory/**

        - id: auth_service
          uri: http://localhost:9898
          predicates:
            - Path=/auth/**
